# Generated by Django 6.0.6 on 2026-06-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedagemInfraestrutura', '0005_categoriaquarto_precobase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorDiaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('tipoTemporada', models.CharField(choices=[('ALTA', 'Alta Temporada'), ('BAIXA', 'Baixa Temporada')], max_length=5)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hospedagemInfraestrutura.categoriaquarto')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['-dataInicio'],
            },
        ),
    ]
