# Generated by Django 6.0.6 on 2026-06-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0008_reserva_identidadeverificada_reserva_observacoes'),
        ('tarifasManutencao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('motivo', models.CharField(choices=[('PREV', 'Preventiva'), ('CORR', 'Corretiva'), ('LIMP', 'Limpeza')], max_length=4)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AGEN', 'Agendada'), ('EMAN', 'Em Andamento'), ('CONC', 'Concluída'), ('CANC', 'Cancelada')], default='EMAN', max_length=4)),
                ('statusAnterior', models.CharField(max_length=4)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='hospedagemInfraestrutura.hotel')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='hospedagemInfraestrutura.quarto')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-dataCriacao'],
            },
        ),
    ]
