@startuml
skinparam shadowing true
skinparam componentStyle uml1
skinparam defaultFontName Arial

left to right direction

skinparam node {
    BackgroundColor White
    BorderColor Black
}
skinparam package {
    BackgroundColor #F8F9FA
    BorderColor #333333
    FontStyle bold
}
skinparam component {
    BackgroundColor White
    BorderColor Black
}
skinparam interface {
    BackgroundColor White
    BorderColor Black
}

node "Cliente: Navegador Web" as n_cliente {
    package "Frontend (React)" {
        component "Interface\nReact SPA" as c_front
    }
}



node "Servidor de Aplicação" as n_servidor {
    
    package "API REST (Django Apps)" {
        interface " " as i_acc
        interface " " as i_hosp
        interface " " as i_fin
        interface " " as i_tar

        component "Controle de\nAcesso" as c_acc
        component "Hospedagem e\nInfraestrutura" as c_hosp
        component "Financeiro" as c_fin
        component "Tarifas e\nManutenção" as c_tar

        i_acc - c_acc
        i_hosp - c_hosp
        i_fin - c_fin
        i_tar - c_tar
    }
}


node "Servidor Banco de Dados" as n_bd {
    
    package "Camada de Dados" {
        interface " " as i_pers
        component "Persistência\n(Django ORM)" as c_orm
        component "SGBD SQLite" as c_sgbd

        i_pers - c_orm
        c_orm ..> c_sgbd
    }
}


n_cliente -- n_servidor : <<HTTP>>
n_servidor -- n_bd : <<Conexão BD>>

c_front ..> i_acc
c_front ..> i_hosp
c_front ..> i_fin
c_front ..> i_tar

c_acc .down.> i_pers
c_hosp .down.> i_pers
c_fin .down.> i_pers
c_tar .down.> i_pers

@enduml