@startuml
skinparam shadowing true
skinparam componentStyle uml1
skinparam defaultFontName Arial
skinparam nodesep 40
skinparam ranksep 60

left to right direction

skinparam node {
    BackgroundColor White
    BorderColor Black
}
skinparam package {
    BackgroundColor #F8F9FA
    BorderColor #333333
    FontStyle bold
}
skinparam component {
    BackgroundColor White
    BorderColor Black
}
skinparam interface {
    BackgroundColor White
    BorderColor Black
}


node "Cliente: Navegador Web" as n_cliente {
    package "Frontend (React SPA)" {
        component "Shared\n(UI Components)" as c_shared_fe
        component "Public" as c_public
        component "Auth" as c_auth_fe
        component "Hóspede" as c_hosp_fe
        component "Admin" as c_admin_fe
        component "Services\n(HTTP Client)" as c_svc_fe

        c_public .left.> c_shared_fe
        c_auth_fe .left.> c_shared_fe
        c_hosp_fe .left.> c_shared_fe
        c_admin_fe ..> c_shared_fe

        c_public .right.> c_svc_fe
        c_auth_fe .right.> c_svc_fe
        c_hosp_fe ..> c_svc_fe
        c_admin_fe ..> c_svc_fe
    }
}


node "Servidor de Aplicação" as n_servidor {
    component "Autenticação\n(SimpleJWT)" as c_jwt

    package "API REST (Django Apps)" {
        interface " " as i_acc
        interface " " as i_hosp
        interface " " as i_fin
        interface " " as i_tar

        component "Controle de Acesso\n--\nViews | Services | Models" as c_acc
        component "Hospedagem e Infra.\n--\nViews | Services | Models" as c_hosp
        component "Financeiro\n--\nViews | Services | Models" as c_fin
        component "Tarifas e Manutenção\n--\nViews | Models" as c_tar

        i_acc - c_acc
        i_hosp - c_hosp
        i_fin - c_fin
        i_tar - c_tar
    }
}


node "Servidor Banco de Dados" as n_bd {
    interface " " as i_db
    component "Persistência\n(Django ORM)" as c_orm
    component "SGBD SQLite3" as c_sgbd

    i_db - c_orm
    c_orm ..> c_sgbd
}

=
node "Serviços Externos" as n_ext {
    component "Gmail SMTP" as c_gmail
}


c_svc_fe ..> c_jwt : Token JWT
c_svc_fe ..> i_acc : REST/JSON
c_svc_fe ..> i_hosp
c_svc_fe ..> i_fin
c_svc_fe ..> i_tar

c_acc ..> i_db
c_hosp ..> i_db
c_fin ..> i_db
c_tar ..> i_db

c_acc .up.> c_gmail : SMTP
c_hosp ..> c_gmail : SMTP

@enduml