@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
skinparam maxmessagesize 150

skinparam sequence {
    LifeLineBorderColor #4A4A4A
    LifeLineBackgroundColor #F9F9F9
    GroupBorderColor #000000
    GroupHeaderFontColor Black
    GroupHeaderBackgroundColor #1565C0
    ActorBorderColor #4A4A4A
    ParticipantBorderColor #4A4A4A
    ParticipantBackgroundColor White
}

actor "Usuário" as user
boundary "view : TelaCadastro" as tela
control "ctrl : CadastroController" as ctrl
entity "usuario : Usuario" as usuario
database "db : BancoDeDados" as db

user -> tela : P.01 acessarTelaCadastro()
activate tela
tela -->> user : P.02 exibirFormularioCadastro()

user -> tela : P.03 informarDados(dadosCadastro)
tela -> ctrl : P.04 validarECadastrar(dadosCadastro)
activate ctrl

ctrl -> ctrl : P.05 validarDados(dadosCadastro)

alt E01: Dados Inválidos
    ctrl -->> tela : E.01 erro("Dados inválidos")
    tela -->> user : E.02 exibirMensagemErro(camposInvalidos)

else P01: Dados Válidos
    ctrl -> db : P.06 verificarEmailExistente(dadosCadastro.email)
    activate db
    db -->> ctrl : P.07 emailExiste ()
    deactivate db

    alt E02: Email já cadastrado
        ctrl -->> tela : E.03 erro("Email já cadastrado")
        tela -->> user : E.04 exibirMensagemErro()

    else P02: Email disponível
        ctrl -> db : P.08 verificarCpfExistente(dadosCadastro.cpf)
        activate db
        db -->> ctrl : P.09 cpfExiste ()
        deactivate db

        alt E03: CPF já cadastrado
            ctrl -->> tela : E.05 erro("CPF já cadastrado")
            tela -->> user : E.06 exibirMensagemErro()

        else P03: CPF disponível
            create entity "novoUsuario : Usuario" as novoUsuario
            ctrl -> novoUsuario : P.10 <<create>> (new Usuario)
            activate novoUsuario
            
            novoUsuario -->> ctrl : P.11 usuarioInstanciado
            
            deactivate novoUsuario

            ctrl -> db : P.12 inserirUsuario(novoUsuario.dados)
            activate db
            db -->> ctrl : P.13 idUsuarioGerado
            deactivate db

            ctrl -->> tela : P.14 cadastroRealizado
            deactivate ctrl

            tela -->> user : P.15 exibirMensagemSucesso()
        end
    end
end

deactivate tela

@enduml
