@startuml
left to right direction

actor "Usuário" as usuario
actor "Hóspede" as hospede

rectangle "Caso de uso - Hóspede"{
    usecase "Visualizar Disponibilidade de Quartos" as visualizar_disponibilidade
    usecase "Verificar Disponibilidade" as verificar_disponibilidade
    usecase "Realizar reserva" as realizar_reserva
    usecase "Cancelar reserva" as cancelar_reserva
    usecase "Realizar Check-in" as realizar_checkin
    usecase "Consultar Extrato de Consumo" as consultar_extrato
    usecase "Realizar Pagamento" as realizar_pagamento
    usecase "Solicitar serviços de quarto" as solicitar_servicos
}

actor "Gateway de Pagamento" as secondary

usuario -- visualizar_disponibilidade
usuario -- realizar_reserva
realizar_reserva ..> verificar_disponibilidade : <<include>>
hospede -- cancelar_reserva
hospede -- realizar_checkin
hospede -- consultar_extrato
hospede -- realizar_pagamento 
hospede -- solicitar_servicos

usuario <|-up- hospede

realizar_pagamento -- secondary

@enduml