# Generated by Django 6.0.6 on 2026-06-21 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedagemInfraestrutura', '0008_reserva_identidadeverificada_reserva_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(choices=[('FRIG', 'Frigobar'), ('SERV', 'Serviço de Quarto'), ('SPA', 'Spa'), ('OUTR', 'Outros')], max_length=4)),
                ('precoAtual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAbertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataFechamento', models.DateTimeField(blank=True, null=True)),
                ('totalAcumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ABER', 'Aberta'), ('PAGA', 'Paga'), ('FECH', 'Fechada'), ('CANC', 'Cancelada')], default='ABER', max_length=4)),
                ('nomeTitular', models.CharField(max_length=255)),
                ('cpfTitular', models.CharField(max_length=14)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='hospedagemInfraestrutura.reserva')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-dataCriacao'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('FRIG', 'Frigobar'), ('SERV', 'Serviço de Quarto'), ('SPA', 'Spa'), ('OUTR', 'Outros')], max_length=4)),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='financeiro.conta')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='financeiro.produto')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-dataHora'],
            },
        ),
    ]
