@startuml

|Usuário|
start
:Acessar opção "Realizar Reserva";

|Sistema SERRÔ|
:Solicitar datas de entrada, saída\ne quantidade de hóspedes;

|Usuário|
:Informar os dados solicitados;

|Sistema SERRÔ|
while (Dados completos e válidos?) is (Não)
    :Exibir mensagem de erro\ncom campos pendentes;
    |Usuário|
    :Corrigir dados;
endwhile

|Sistema SERRÔ|
:Consultar disponibilidade de Quartos;



|Sistema SERRÔ|
if (Quartos disponíveis e liberados?) then (Sim)
    :Obter tarifa vigente;
    :Calcular valor total da estadia;
    :Exibir opções de quartos e resumo de valores;
else (Não)
    :Exibir mensagem:\n"Não há quartos disponíveis para o período";
    stop
endif

|Usuário|
:Selecionar quarto;

if (Confirmar intenção de reserva?) then (Não)

    |Sistema SERRÔ|
    :Limpar dados temporários da sessão;
    :Redirecionar para tela inicial;
    stop

else (Sim)
    :Exibir tela de resumo da Reserva;
endif

|Sistema SERRÔ|

fork
    :Vincular Quarto à Reserva;
    :Gerar código único da Reserva;
fork again
    :Abrir nova Conta de Hospedagem;
fork again
    :Enviar voucher de confirmação\npor e-mail;
end fork

stop
@enduml