# Generated by Django 6.0.6 on 2026-06-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controleDeAcesso', '0003_alter_endereco_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefoneContato', models.CharField(max_length=20)),
                ('emailContato', models.EmailField(max_length=254)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controleDeAcesso.endereco')),
                ('gestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controleDeAcesso.gestor')),
            ],
        ),
    ]
