# Generated by Django 6.0.6 on 2026-06-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0003_alter_hotel_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('capacidade', models.PositiveIntegerField()),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='hospedagemInfraestrutura.hotel')),
            ],
            options={
                'verbose_name_plural': 'categorias de quarto',
                'unique_together': {('hotel', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('andar', models.IntegerField()),
                ('status', models.CharField(choices=[('DISP', 'Disponível'), ('OCUP', 'Ocupado'), ('LIMP', 'Em Limpeza'), ('MANU', 'Em Manutenção')], default='DISP', max_length=4)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='hospedagemInfraestrutura.categoriaquarto')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='hospedagemInfraestrutura.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'numero')},
            },
        ),
    ]
