# Generated by Django 6.0.6 on 2026-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0004_categoriaquarto_quarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaquarto',
            name='precoBase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
