# Generated by Django 6.0.6 on 2026-06-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0005_categoriaquarto_precobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('dataEntrada', models.DateField()),
                ('dataSaida', models.DateField()),
                ('numHospedes', models.PositiveIntegerField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CONF', 'Confirmada'), ('CANC', 'Cancelada'), ('FINA', 'Finalizada')], default='CONF', max_length=4)),
                ('dataReserva', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hospedagemInfraestrutura.categoriaquarto')),
                ('hospede', models.ForeignKey(limit_choices_to={'role': 'HO'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hospedagemInfraestrutura.hotel')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='hospedagemInfraestrutura.quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-dataReserva'],
            },
        ),
    ]
