# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0006_quarto_status_changed_at_quarto_status_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(
                choices=[
                    ('PEND', 'Pendente'),
                    ('CONF', 'Confirmada'),
                    ('CHIN', 'Check-in'),
                    ('FINA', 'Finalizada'),
                    ('CANC', 'Cancelada'),
                ],
                default='PEND',
                max_length=4,
            ),
        ),
    ]
