# Generated by Django 6.0.6 on 2026-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagemInfraestrutura', '0007_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='identidadeVerificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
