@startuml
left to right direction

actor "Gestor" as g

rectangle "Sistema SERRÔ - Módulo de Gestão e BI" {
    usecase "Autenticar Gestor" as auth
    
        usecase "Consultar Dashboard Geral" as uc17
        usecase "Gerar Relatório de Faturamento" as uc18
        usecase "Gerar Relatório de Ocupação" as uc19
        usecase "Gerenciar Tarifas de Temporada" as uc20


    g -- uc17
    g -- uc18
    g -- uc19
    g -- uc20

    uc17 ..> auth : <<include>>
    uc18 ..> auth : <<include>>
    uc19 ..> auth : <<include>>
    uc20 ..> auth : <<include>>
}

@enduml