@startuml
left to right direction

actor "Gestor" as g
actor "Supervisor" as supervisor

rectangle "Caso de uso - Gestor" {
    usecase "Consultar Dashboard" as uc17
    usecase "Gerar Relatório de Faturamento" as uc18
    usecase "Gerar Relatório de Ocupação" as uc19
    usecase "Gerenciar Tarifas de Temporada" as uc20

    g -- uc17
    g -- uc18
    g -- uc19
    g -- uc20

    supervisor <|-right- g
}

@enduml