@startuml
left to right direction

actor "Usuário" as usuario
actor "Supervisor" as supervisor

rectangle "Caso de uso - Supervisor" {
    usecase "Manter Quartos" as uc13
    usecase "Gerenciar Categorias de Acomodação" as uc14
    usecase "Gerenciar Comodidades" as uc15
    usecase "Bloquear/Desbloquear para Manutenção/Limpeza" as uc16


    supervisor -- uc13
    supervisor -- uc14
    supervisor -- uc15
    supervisor -- uc16

    usuario <|-right- supervisor
}
@enduml