@startuml
left to right direction

actor "Supervisor" as supervisor


rectangle "Caso de uso - Supervisor" {
    usecase "Autenticar Usuário" as auth

    usecase "Manter Quartos" as uc13
    usecase "Gerenciar Categorias de Acomodação" as uc14
    usecase "Gerenciar Comodidades" as uc15
    usecase "Bloquear/Desbloquear para Manutenção" as uc16


    supervisor -- uc13
    supervisor -- uc14
    supervisor -- uc15
    supervisor -- uc16


    uc13 ..> auth : <<include>>
    uc14 ..> auth : <<include>>
    uc15 ..> auth : <<include>>
    uc16 ..> auth : <<include>>

}
@enduml