# Generated by Django 6.0.6 on 2026-06-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14, unique=True)),
                ('dataNascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SV', 'Supervisor'), ('GE', 'Gestor'), ('AT', 'Atendente'), ('HO', 'Hóspede')], max_length=2)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleDeAcesso.endereco')),
            ],
        ),
    ]
