# Generated by Django 6.0.6 on 2026-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0002_atendente_supervisor_hospede_alter_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
