# Generated by Django 6.0.6 on 2026-06-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0003_alter_endereco_complemento'),
        ('hospedagemInfraestrutura', '0003_alter_hotel_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospedagemInfraestrutura.hotel'),
        ),
    ]
