# Generated by Django 6.0.6 on 2026-06-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0004_usuario_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendente',
            options={'verbose_name': 'Atendente', 'verbose_name_plural': 'Atendentes'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name': 'Gestor', 'verbose_name_plural': 'Gestores'},
        ),
        migrations.AlterModelOptions(
            name='hospede',
            options={'verbose_name': 'Hóspede', 'verbose_name_plural': 'Hóspedes'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
